[package]
name = "linear"
version = "0.2.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/hilbert-space/linear"
homepage = "https://github.com/hilbert-space/linear"
description = "Use the matrix package instead."
